# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ef66333bda745b0734bb9cf70f23a9da97045c59814b62640af0dafa47d0b1c04495a403c318dc0f6a4e66720ee61e20316ce856270f0a60d1b58dbf5c575f

test:
  secret_key_base: 22a311b5b3d649cc71eb2c15a0a8301b5e1e39b07bb85d245c3693444676dde3da7b5945766f4c70df2eb80173dcbd446208beeb640fcbd789a312981a1d5bec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
